### ISSUE TITLE
indent subsequent lines of each menu item

### ISSUE THREAD

**Issue by peterrentz** [chrisladd/lunchbot#6]
The list could use some formating for easier reading. Can the list be renders as an unordered list?
![lunchbot](https://cloud.githubusercontent.com/assets/1116508/13964493/5cd1fc12-f040-11e5-88de-66cb6ee26933.png)

**Comment by chrisladd** [comment]
love it.

**Comment by chrisladd** [comment]
Fixed!

**Comment by peterrentz** [comment]
wow thanks Chris!
