### ISSUE TITLE
Error message suggestions

### ISSUE THREAD

**Issue by peterrentz** [chrisladd/lunchbot#7]
- Lunchbot is out to lunch, come back later
- Lunchbot is on strike
- Lunchbot is lobbying for a minimum wage
- Four Oh Four Oh Friggin Hell

**Comment by chrisladd** [comment]
![screen shot 2016-04-13 at 2 23 42 pm](https://cloud.githubusercontent.com/assets/275551/14504565/5ecbe8d0-0183-11e6-98ed-23b145672ead.png)
